[theme]
primaryColor="#7F00FF"      # Roxo vibrante (exemplo)
backgroundColor="#FFFDF9"    # Fundo claro (exemplo)
secondaryBackgroundColor="#F0F2F6" # Fundo da sidebar (exemplo)
textColor="#31333F"         # Cor do texto principal (exemplo)
font="sans serif"            # Tipo de fonte base